CREATE DATABBASE alurageek;

CREATE TABLE IF NOT EXISTS category(
  id SMALLINT NOT NULL UNIQUE PRIMARY KEY,
  name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS product(
  id SMALLINT NOT NULL UNIQUE PRIMARY KEY,
  name VARCHAR NOT NULL UNIQUE,
  price DECIMAL NOT NULL,
  photo VARCHAR,
  category_id SMALLINT,
  FOREIGN KEY(category_id) REFERENCES category(id)
);
